### ISSUE TITLE
SQRL Wallet needs Telos Decide Works instructions for claiming post claim button click 

### ISSUE THREAD

**Issue by ackza** [telosnetwork/sqrl#11]
SQRL still tells me its making a  "Deposit" after I claim on the WPS , but my proposal money doesnt show up unless I go and claim it on the telos decide smart contract using telos.bloks.io Which is cool but the Post Claim SQRL window that pops up telling us its Making a one time deposit, should maybe instead give the link like DOuglas had to do for me here :D 

![image](https://user-images.githubusercontent.com/33010254/90210134-0c5bba80-dda2-11ea-8d05-3a3a0767acc0.png)
****

![image](https://user-images.githubusercontent.com/33010254/90210160-1c739a00-dda2-11ea-9d98-93088f8c2a14.png)

Transcript for Reference when I asked how to claim my Telos Decide proposal fees: 
Gv, [13.08.20 16:04]
How do you withdraw funds after a successful first milestone?

Douglas Horn | GoodBlock.io, [13.08.20 16:18]
[In reply to Ackza SAND TLOS KANDA eos: zackzackzack Telos Kanda EOSIO HIVE]
Hi Zack. You just have to withdraw. Your funds are waiting for you.

https://telos.bloks.io/account/works.decide?loadContract=true&tab=Tables&table=accounts&account=works.decide&scope=ackzaontelos&limit=100

Douglas Horn | GoodBlock.io, [13.08.20 16:20]
Sign in to bloks with your ackzaontelos account. Go here and put in your account name and '2075.0000 TLOS' and you'll get it.

https://telos.bloks.io/account/works.decide?loadContract=true&tab=Actions&table=accounts&account=works.decide&scope=ackzaontelos&limit=100&action=withdraw

Douglas Horn | GoodBlock.io, [13.08.20 16:21]
I need to do a video I guess...

Douglas Horn | GoodBlock.io, [13.08.20 16:22]
I'll try to remember to record it when I do the next round of claiming and submitting the TCD proposal.

**Comment by marlonwilliams** [comment]
This has been resolved in v1.2.3
