### ISSUE TITLE
Worker proposal submission failing with account string required assertion

### ISSUE THREAD

**Issue by firmwareguru** [telosnetwork/sqrl#5]
I've cloned this repo right from master and have been running in development mode with `yarn dev`.

I notice that in the Worker Proposal form, there is no `recipient` field to put an account to receive funds.  When submitting the proposal, it fails with an "account string required" assertion:

<img width="283" alt="sqrl-account-string-required" src="https://user-images.githubusercontent.com/22859127/82914507-d4747200-9f2c-11ea-879d-17b67857e20e.png">

Can you point me to a released version I should be using that works?  Thanks

**Comment by marlonwilliams** [comment]
Version 1.2.1 works with the latest Telos Works system. Here's a video:
https://www.youtube.com/watch?v=RyA9dG8Rnek

-Marlon

**Comment by firmwareguru** [comment]
Thank you @marlonwilliams, the 1.2.1 release works great.  This is most likely a non-issue so I'll close it.

**Comment by marlonwilliams** [comment]
Awesome. Thanks, Evan!

-Marlon
