### ISSUE TITLE
Receive account not found message after account created

### ISSUE THREAD

**Issue by dellams** [telosnetwork/sqrl#8]
Hello,

I hope someone can help?

I created an account through your GUI and it was successfully created with my public, private keys etc but when I then try to login through the "Look Up Account" screen I get a error message saying it was not found.

Any ideas?

I also tried logging in with both of the public keys that were generated (active and owner). What is the difference between these anyway?

My account name is: oasisapitest and it was created on the Telos Testnet.

Any help would be really appreciated.

Many thanks,
David.

**Comment by marlonwilliams** [comment]
As discussed, free account is not supported on testnet. This is a useful link for future reference: https://app.telos.net/
